version: '3'

services:
  server:
    build: server
    ports:
      - "8080:8080"
    volumes:
      - "./server:/workspace"
    depends_on:
      - db
    networks:
      - area
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_HOST=db
      - MONGODB_DB=${MONGODB_DB}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_ID=${GOOGLE_ID}
      - TRELLO_KEY=${TRELLO_KEY}
      - TRELLO_SECRET=${TRELLO_SECRET}
      - OFFICE_KEY=${OFFICE_KEY}
      - OFFICE_SECRET=${OFFICE_SECRET}
      - OFFICE_TENANT=${OFFICE_TENANT}
    command: bash -c 'npm install && nodemon -L server.js'
    restart: unless-stopped

  client_web:
    build: client_web
    ports:
      - "8081:3000"
    volumes:
      - "./client_web:/workspace"
    depends_on:
      - server
    networks:
      - area
    environment:
      - BACKEND_URL=${BACKEND_URL}
    command: bash -c 'npm install && npm start'
    restart: unless-stopped

  db:
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - "db-data:/data/db"
    networks:
      - area
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${MONGODB_DB}
    restart: unless-stopped

volumes:
  db-data:

networks:
  area:
